---
- job:
    name: pipeline-infra
    project-type: pipeline
    triggers:
      - timed: "30 0 * * *"
    dsl: |
      stage('post-update-jenkins') {
          catchError {
              build job: 'post-update-jenkins'
          }
          echo currentBuild.result
      }
